[package]
name = "arp-scanner"
version = "0.2.0"
authors = ["Gavyn Riebau <gavyn.riebau@gmail.com>"]

[dependencies]
pnet_datalink = "0.21.0"
ipnetwork = "0.12.0"
prettytable-rs = "0.7.0"
clap = "2.31.2"

[dependencies.pnet]
version = "0.21.0"
